### ISSUE TITLE
Rework side panel / classic view mode, fix inconsistencies with the Server Browser (sub-tasks)

### ISSUE THREAD

**Issue by Zatline** [teeworlds/teeworlds#3203]
follow up of task 1 in #3161, sub-tasks:

- [ ] #3201 
- [ ] Remove round corners of the selected column and make it more white
- [ ] #3200 
- [ ] Remove the wide view button in the top right
- [ ] #3202
- [ ] Improve filter UI in the side panel
- [ ] Improve friends/clan UI in the side panel

(...)

**improved design** mockups:
![Srv Browser - Classic View](https://github.com/teeworlds/teeworlds/assets/344608/5e1a33f7-c3f0-447f-b68c-fe9b7157608a)
![Srv Browser - Classic View – 1](https://github.com/teeworlds/teeworlds/assets/344608/371b3f27-2e74-4ecd-aba4-3a9e6d612f0e)
![Srv Browser - Classic View – 2](https://github.com/teeworlds/teeworlds/assets/344608/0d6fcd3b-7aea-4dd2-b892-38e8075ccf78)
